#!/bin/sh
# Having trouble with xmobar's volume and alsa plugins
# So here's a script for volume info instead

volume="$(amixer get Master | tail -1 | awk '{print $5}' | sed -e 's/[^0-9]//g')"
mute="$(amixer get Master | tail -1 | awk '{print $6}' | sed -e 's/[^a-z]//g')"

if [[ "$mute" == "off" ]]; then
  echo "<fn=1></fn>"
elif [ "$volume" -lt 30 ]; then
  echo "<fn=1></fn> <fc=darkred>$volume</fc>"
elif [ "$volume" -lt 60 ]; then
  echo "<fn=1></fn> <fc=darkorange>$volume</fc>"
else
  echo "<fn=1></fn> <fc=darkgreen>$volume</fc>"
fi
